### ISSUE TITLE
Error fetching data.

### ISSUE THREAD

**Issue by krestaino** [leonlarsson/the-finals-leaderboard#15]
Looks like the API is having issues. Can't currently view the leaderboards.

**Comment by leonlarsson** [comment]
Looking into it

**Comment by leonlarsson** [comment]
This has now been fixed.

The error was caused by a change in the Embark data structure:

- Instead of strings as keys, all keys are now numbers.
- Instead of `""` for empty platform names, a `0` is now reported

I have updated the data transformer in https://github.com/leonlarsson/the-finals-api to handle these new cases.
I have also updated this project for the one instance that was affected.
